name: Check and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: {}


jobs:
  run_tests:
    strategy:
      matrix:
        python-version: [ "3.10", "3.11" ]

    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies
        run: |
          python -m pip install --upgrade setuptools
          python -m pip install -r requirements.txt
          python -m pip install -e .[test]

      - name: Run checks and tests
        run: |
          make flake
          pytest ./tests
